name: nanopore
channels:
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20211102.0=he9d5cce_0
  - anyio=3.5.0=py311hecd8cb5_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - appnope=0.1.2=py311hecd8cb5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py311h6c40b1e_0
  - arrow-cpp=11.0.0=py311hb8cef1d_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - attrs=22.1.0=py311hecd8cb5_0
  - aws-c-common=0.4.57=hb1e8313_1
  - aws-c-event-stream=0.1.6=h23ab428_5
  - aws-checksums=0.1.9=hb1e8313_0
  - aws-sdk-cpp=1.8.185=he271ece_0
  - babel=2.11.0=py311hecd8cb5_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.12.2=py311hecd8cb5_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bokeh=3.1.1=py311h85bffb1_0
  - boost-cpp=1.73.0=hca72f7f_12
  - bottleneck=1.3.5=py311hb9e55a9_0
  - brotli=1.0.9=hca72f7f_7
  - brotli-bin=1.0.9=hca72f7f_7
  - brotlipy=0.7.0=py311h6c40b1e_1002
  - bzip2=1.0.8=h1de35cc_0
  - c-ares=1.19.0=h6c40b1e_0
  - ca-certificates=2023.05.30=hecd8cb5_0
  - certifi=2023.5.7=py311hecd8cb5_0
  - cffi=1.15.1=py311h6c40b1e_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.4=py311hecd8cb5_0
  - cloudpickle=2.2.1=py311hecd8cb5_0
  - comm=0.1.2=py311hecd8cb5_0
  - contourpy=1.0.5=py311ha357a0b_0
  - cryptography=39.0.1=py311hf6deb26_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cytoolz=0.12.0=py311h6c40b1e_0
  - dask=2023.6.0=py311hecd8cb5_0
  - dask-core=2023.6.0=py311hecd8cb5_0
  - debugpy=1.5.1=py311hcec6c5f_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distributed=2023.6.0=py311hecd8cb5_0
  - entrypoints=0.4=py311hecd8cb5_0
  - executing=0.8.3=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=hd8bbffd_0
  - fsspec=2023.4.0=py311hecd8cb5_0
  - gflags=2.2.2=h0a44026_0
  - giflib=5.2.1=h6c40b1e_3
  - glog=0.5.0=h23ab428_0
  - grpc-cpp=1.46.1=h64d96ca_1
  - h5py=3.7.0=py311h4bbaca6_0
  - hdf5=1.10.6=h10fe05b_1
  - heapdict=1.0.1=pyhd3eb1b0_0
  - icu=58.2=h0a44026_3
  - idna=3.4=py311hecd8cb5_0
  - importlib-metadata=6.0.0=py311hecd8cb5_0
  - intel-openmp=2023.1.0=ha357a0b_43547
  - ipykernel=6.19.2=py311h4975b63_0
  - ipython=8.12.0=py311hecd8cb5_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=8.0.4=py311hecd8cb5_0
  - jedi=0.18.1=py311hecd8cb5_1
  - jinja2=3.1.2=py311hecd8cb5_0
  - jpeg=9e=h6c40b1e_1
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.17.3=py311hecd8cb5_0
  - jupyter_client=8.1.0=py311hecd8cb5_0
  - jupyter_core=5.3.0=py311hecd8cb5_0
  - jupyter_events=0.6.3=py311hecd8cb5_0
  - jupyter_server=2.5.0=py311hecd8cb5_0
  - jupyter_server_terminals=0.4.4=py311hecd8cb5_0
  - jupyterlab=3.5.3=py311hecd8cb5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.22.0=py311hecd8cb5_0
  - jupyterlab_widgets=3.0.5=py311hecd8cb5_0
  - kiwisolver=1.4.4=py311hcec6c5f_0
  - krb5=1.20.1=hdba6334_1
  - lcms2=2.12=hf1fd2bf_0
  - lerc=3.0=he9d5cce_0
  - libboost=1.73.0=h3fa6bed_12
  - libbrotlicommon=1.0.9=hca72f7f_7
  - libbrotlidec=1.0.9=hca72f7f_7
  - libbrotlienc=1.0.9=hca72f7f_7
  - libcurl=8.1.1=ha585b31_1
  - libcxx=14.0.6=h9765a3e_0
  - libdeflate=1.17=hb664fd8_0
  - libedit=3.1.20221030=h6c40b1e_0
  - libev=4.33=h9ed2024_1
  - libevent=2.1.12=h0a4fc7d_0
  - libffi=3.4.4=hecd8cb5_0
  - libgfortran=5.0.0=11_3_0_hecd8cb5_28
  - libgfortran5=11.3.0=h9dfd629_28
  - libiconv=1.16=hca72f7f_2
  - libnghttp2=1.52.0=h1c88b7d_1
  - libpng=1.6.39=h6c40b1e_0
  - libprotobuf=3.20.3=hfff2838_0
  - libsodium=1.0.18=h1de35cc_0
  - libssh2=1.10.0=hdb2fb19_2
  - libthrift=0.15.0=h48f73ad_2
  - libtiff=4.5.0=hcec6c5f_2
  - libuv=1.44.2=h6c40b1e_0
  - libwebp=1.2.4=hf6ce154_1
  - libwebp-base=1.2.4=h6c40b1e_1
  - libxml2=2.10.3=h930c0e2_0
  - libxslt=1.1.37=h6d1eb0e_0
  - llvm-openmp=14.0.6=h0dcd299_0
  - locket=1.0.0=py311hecd8cb5_0
  - lxml=4.9.2=py311h6c40b1e_0
  - lz4=4.3.2=py311h6c40b1e_0
  - lz4-c=1.9.4=hcec6c5f_0
  - markupsafe=2.1.1=py311h6c40b1e_0
  - matplotlib=3.7.1=py311hecd8cb5_1
  - matplotlib-base=3.7.1=py311h11e8b89_1
  - matplotlib-inline=0.1.6=py311hecd8cb5_0
  - mistune=0.8.4=py311h6c40b1e_1000
  - mkl=2023.1.0=h59209a4_43558
  - mkl-service=2.4.0=py311h6c40b1e_1
  - mkl_fft=1.3.6=py311hdb55bb0_1
  - mkl_random=1.2.2=py311hdb55bb0_1
  - msgpack-python=1.0.3=py311ha357a0b_0
  - munkres=1.1.4=py_0
  - nbclassic=0.5.5=py311hecd8cb5_0
  - nbclient=0.5.13=py311hecd8cb5_0
  - nbconvert=6.5.4=py311hecd8cb5_0
  - nbformat=5.7.0=py311hecd8cb5_0
  - ncurses=6.4=hcec6c5f_0
  - nest-asyncio=1.5.6=py311hecd8cb5_0
  - nodejs=18.15.0=hab5cffc_0
  - notebook=6.5.4=py311hecd8cb5_0
  - notebook-shim=0.2.2=py311hecd8cb5_0
  - numexpr=2.8.4=py311h728a8a3_1
  - numpy=1.24.3=py311h728a8a3_1
  - numpy-base=1.24.3=py311h53bf9ac_1
  - openssl=1.1.1u=hca72f7f_0
  - orc=1.7.4=h995b336_1
  - packaging=23.0=py311hecd8cb5_0
  - pandas=1.5.3=py311hc5848a5_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - partd=1.2.0=pyhd3eb1b0_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.4.0=py311hcec6c5f_0
  - pip=23.0.1=py311hecd8cb5_0
  - platformdirs=2.5.2=py311hecd8cb5_0
  - plotly=5.14.1=pyhd8ed1ab_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - prometheus_client=0.14.1=py311hecd8cb5_0
  - prompt-toolkit=3.0.36=py311hecd8cb5_0
  - psutil=5.9.0=py311h6c40b1e_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyarrow=11.0.0=py311hf41f4e6_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py311hecd8cb5_1
  - pyopenssl=23.0.0=py311hecd8cb5_0
  - pyparsing=3.0.9=py311hecd8cb5_0
  - pyrsistent=0.18.0=py311h6c40b1e_0
  - pysocks=1.7.1=py311hecd8cb5_0
  - python=3.11.3=h1fd4e5f_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py311hecd8cb5_0
  - python-json-logger=2.0.7=py311hecd8cb5_0
  - python-lmdb=1.4.1=py311hcec6c5f_0
  - pytz=2022.7=py311hecd8cb5_0
  - pyyaml=6.0=py311h6c40b1e_1
  - pyzmq=25.0.2=py311hcec6c5f_0
  - re2=2022.04.01=he9d5cce_0
  - readline=8.2=hca72f7f_0
  - requests=2.29.0=py311hecd8cb5_0
  - rfc3339-validator=0.1.4=py311hecd8cb5_0
  - rfc3986-validator=0.1.1=py311hecd8cb5_0
  - scipy=1.10.1=py311h224febf_1
  - seaborn=0.12.2=py311hecd8cb5_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=67.8.0=py311hecd8cb5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.9=he9d5cce_0
  - sniffio=1.2.0=py311hecd8cb5_1
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.4=py311hecd8cb5_0
  - sqlite=3.41.2=h6c40b1e_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=ha357a0b_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - tenacity=8.2.2=py311hecd8cb5_0
  - terminado=0.17.1=py311hecd8cb5_0
  - tinycss2=1.2.1=py311hecd8cb5_0
  - tk=8.6.12=h5d9f67b_0
  - tomli=2.0.1=py311hecd8cb5_0
  - toolz=0.12.0=py311hecd8cb5_0
  - tornado=6.2=py311h6c40b1e_0
  - traitlets=5.7.1=py311hecd8cb5_0
  - typing-extensions=4.5.0=py311hecd8cb5_0
  - typing_extensions=4.5.0=py311hecd8cb5_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.15=py311hecd8cb5_0
  - utf8proc=2.6.1=h9ed2024_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py311hecd8cb5_1
  - websocket-client=0.58.0=py311hecd8cb5_4
  - wheel=0.38.4=py311hecd8cb5_0
  - widgetsnbextension=4.0.5=py311hecd8cb5_0
  - xyzservices=2022.9.0=py311hecd8cb5_1
  - xz=5.4.2=h6c40b1e_0
  - yaml=0.2.5=haf1e3a3_0
  - zeromq=4.3.4=h23ab428_0
  - zict=2.2.0=py311hecd8cb5_0
  - zipp=3.11.0=py311hecd8cb5_0
  - zlib=1.2.13=h4dc903c_0
  - zstd=1.5.5=hc035e20_0
  - pip:
      - bcrypt==4.1.2
      - paramiko==3.4.0
      - pynacl==1.5.0
prefix: /Users/daphnekontogiorgos-heintz/opt/anaconda3/envs/nanopore
